#!/usr/bin/env python
import argparse
import sys

from _npmanager.manager import Manager

def main():
    parser = argparse.ArgumentParser()
    args = parser.parse_args()

    manager = Manager()
    manager.install()

    sys.exit(0)


if __name__ == '__main__':
    main()
